name: Publish Package
on:
  push:
    branches:
      - "main"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Install dependencies
        run: yarn
      - name: run semantic release
        run: yarn release
        env:
          GITHUB_TOKEN: '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'
