name: Publish Package
on:
  push:
    branches:
      - "main"
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Install dependencies
        run: yarn
      - name: run semantic release
        run: yarn release