name: Publish Package
on:
  push:
    branches:
      - "main"
jobs:
  release-to-registries:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: run semantic release
        run: yarn && yarn release
        env:
          GITHUB_TOKEN: '${{ secrets.USE_GITHUB_TOKEN }}'